tasks:
  - init: |
      cp apps/api/.env.example deploy/docker/.env
      docker compose -f deploy/docker/docker-compose.yml pull
  - command: | 
      docker compose -f deploy/docker/docker-compose.yml up


ports:
  - port: 5700
    onOpen: open-browser
  - port: 5801
    onOpen: open-browser
  - port: 5800
    onOpen:  open-browser
  - port: 9300
    onOpen: ignore
  - port: 9600
    onOpen: ignore

vscode:
  extensions:
    - ms-azuretools.vscode-docker