import { Feed } from "@/types/feed"

export const fakeFeedList: Feed[] = [
  {
    id: "65fc361995de0ee1341fe280",
    userId: "65fc2a2196ea5f02878995b2",
    title: "Mental Health in Open Source",
    lastMessage:
      "# Mental Health in Open Source\n\nAnthony Fu @ antfu.me\n\n**TL;DR:** 我目前状况良好，不会离开。虽然有一些压力，但仍在努力保持并改进。谢谢大家，不用担心！\n\n这是我开始做开源的第四年。坦率地说，我开始感觉自己的能力越来越不足以胜任。我不确定自己是否曾经经历过真正的燃尽，但我确实周期性地经历过生产力和动力的起伏。\n\n这篇文章不是指南，也不是抱怨。更像是我的个人日记，我把它作为自己的记录。我觉得如果能与大家分享这些可能会很有趣。\n\n如果你经历过燃尽或感觉接近燃尽，我建议你休息一下，与他人交谈，并在需要时寻求专业帮助。这里还有一篇不错的文章《为开源维护者保持平衡》，你可以参考一下。请好好照顾自己！\n\n在某种程度上，开源对我来说仍然很新。自从我开始学习编程和了解开源以来，我就一直梦想成为全职开源开发者。当我还在上大学时，我渴望得到开源社区的认可，努力“想出”一些有影响力的工作。突然间，你会达到一个关键点，在这一刻，你的项目可能会意外地起飞，或者你被邀请加入一个大项目 - 你会开始感受到所有这些兴奋以及突然而来的责任。几天后，当最初的兴奋开始消退时，你开始意识到这也意味着很多责任和其他你从未考虑过的事情。尽管我在大学时一直努力想进入开源，但当我最终踏入其中时，我意识到自己有多么不成熟。\n\n开源的一个有趣之处在于，你可能永远不会准备好。你可能会遇到棘手的技术问题，或者不得不跟上新技术的步伐，但除了编码之外，你还必须处理许多其他事情。你必须成为自己的客户支持，回答问题；成为设计师、写手，准备好文档；成为项目经理，确保项目按计划进行；成为团队领导，吸引新贡献者并保持团队积极性；推广你的东西；在会议上演讲等等。这些都是成为开源开发者的“副作用”，许多事情一起涌向你，不仅仅是代码。\n\n对我来说，这是一个巨大的挑战。我很内向，不擅长聊天或交谈。我在学校英语考试时表现糟糕，对于用英语讲话毫无信心。即使只是在同学面前，我也会紧张。我想我也不喜欢团队管理，尽管我从未领导过团队 - 有太多事情让我害怕。\n\n它不会给你准备好的时间（或者另一方面，没有第一步，你可能永远不会准备好），随着项目的增长，随着责任的增加，你将被迫学习和适应。当自然而然地组建一个团队时，你必须学会沟通、领导。当有人邀请你做播客或演讲时，他们不会等待你练习语言或演讲技巧3年 - 你要么错过机会，要么战胜恐惧去做。因为我如此热爱开源，我不得不征服它们和自己。\n\n看起来可能会让人不知所措。但如果你逐个克服这些挑战，逐渐地，你可能会发现它们非常有趣和有益。最后，我非常感激所有那些推动我走出舒适区、迫使我改进的机会。在这4年的开源之旅中，尽管在许多方面仍然不完美，我成功地更自信地讲英语。我在许多会议上发表演讲，其中一些甚至有数千名与会者。每次演讲前我仍然非常紧张，但至少我不再害怕这样做。\n\n还有许多挑战和惊喜在等着我。我一半害怕一半兴奋地期待着接下来会发生什么。",
    messageCount: 2,
    origin: "https://antfu.me",
    originPageUrl: "https://antfu.me/posts/mental-health-oss",
    originPageTitle: "Mental Health in Open Source",
    createdAt: "2024-03-21T13:28:57.888Z",
    updatedAt: "2024-03-21T13:29:32.826Z",
  },
  {
    id: "65fc360095de0ee1341fe27e",
    userId: "65fc2a2196ea5f02878995b2",
    title: "Mental Health in Open Source",
    lastMessage: "",
    messageCount: 0,
    origin: "https://antfu.me",
    originPageUrl: "https://antfu.me/posts/mental-health-oss",
    originPageTitle: "Mental Health in Open Source",
    createdAt: "2024-03-21T13:28:32.247Z",
    updatedAt: "2024-03-21T13:28:32.247Z",
  },
  {
    id: "65fc35ff95de0ee1341fe27b",
    userId: "65fc2a2196ea5f02878995b2",
    title: "Mental Health in Open Source",
    lastMessage:
      '# Mental Health in Open Source\n\nAnthony Fu @ antfu.me\n\n**TL;DR:** 我目前状况良好，不会离开。虽然有一些压力，但仍在努力保持并改进。谢谢大家，不用担心！\n\n这是我开始从事开源工作的第四年。坦率地说，我开始感觉自己的能力越来越不足以胜任。我不确定自己是否曾经经历过真正的疲劳，但我确实周期性地经历过生产力和动力的起伏。\n\n这篇文章不是指南，也不是抱怨。更像是我的个人日记，我把它作为自己的记录。我觉得如果能与大家分享这些可能会很有趣。\n\n如果你经历过疲劳或感觉接近疲劳，我建议你休息一下，与他人交谈，并在需要时寻求专业帮助。这里还有一篇不错的文章《为开源维护者保持平衡》，你可以参考一下。请好好照顾自己！\n\n现在，让我告诉你最近我一直在思考的一些事情\n\n**未准备** # 在某种程度上，对我来说，开源仍然很新颖，即使在今天。\n\n自从我开始学习编程和了解开源以来，我就一直梦想成为全职开源开发者。当我还在上大学时，我渴望得到开源社区的认可，努力“想出”一些有影响力的工作。突然间，你会达到一个关键点，在这一刻，你的项目可能会意外地起飞，或者你被邀请加入一个大项目 - 一瞬间，你会开始感受到所有这些兴奋以及突然而来的责任。几天后，当最初的兴奋开始消退时，你开始意识到这也意味着很多责任和其他你从未考虑过的事情。尽管我在大学时一直努力想进入开源，但当我最终踏入其中时，我意识到自己有多么不成熟。\n\n开源的一个有趣之处在于，你可能永远不会准备好。你可能会遇到棘手的技术问题，或者必须跟上新技术的发展，但除了编码之外，你还必须处理许多其他事情。你必须成为自己的客户支持来回答问题；成为设计师、写手来准备良好的文档；成为项目经理来保持项目进展顺利；成为团队领导来吸引新贡献者并保持团队积极性；推广你的东西；在会议上演讲等等。这些都是成为开源开发者的“副作用”，许多事情一起降临在你身上，不仅仅是编码。\n\n对我来说，这是一个巨大的挑战。我很内向，不擅长聊天或交谈。我在学校英语考试时表现糟糕，对于讲英语毫无信心。即使只是在同学面前，我也会紧张得要命。我想我也不喜欢团队管理，尽管我从未领导过团队 - 有太多事情让我害怕。\n\n它不会给你准备的时间（或者另一方面，如果不迈出第一步，你可能永远不会准备好），随着项目的增长，随着你的责任增加，你将被迫学习和适应。当自然地组建一个团队时，你必须学会沟通，领导。当有人邀请你做播客或演讲时，他们不会等待你练习语言或演讲技巧3年 - 你要么错过机会，要么战胜恐惧去做。因为我如此热爱开源，我不得不征服它们和自己。\n\n看起来可能会让人不知所措。但如果你逐个挑战并逐个克服它们，逐渐地，你可能会发现它们是相当有趣和有益的。最后，我非常感激所有那些推动我走出舒适区并迫使我改进的机会。在这4年的开源之旅中，尽管在许多方面仍然不完美，我成功地更自信地讲英语。我在许多会议上发表演讲，其中一些甚至有数千名与会者。每次演讲前我仍然非常紧张，但至少我不再害怕这样做。\n\n还有许多挑战和惊喜在等着我。我一半害怕一半兴奋地期待着接下来会发生什么。\n\n**期望** # 人类适应。这驱使我们生存并不断进步，但也使我们难以满足。\n\n当我开始我的前几个开源项目时，我非常兴奋。我会不断刷新页面，急切地等待新问题、新拉取请求和新评论的出现。每一个星星都会让我开心，我会尽可能帮助每一个问题。我设定了里程碑，比如100颗星，500颗星，当我达到时我会庆祝。我仍然记得当我告诉朋友我的项目有几百颗星星，我对世界产生了一些影响时我有多自豪。\n\n一旦达到这些目标，事情开始变得“平常”。然后你会开始期待更多并设定更高的目标。在某个时刻，我开始不再关心那些星星或下载量的数字。这并不一定是坏事，因为它们并不是我应该关注的指标，但有时我会怀念那些简单事物带给我的快乐。\n\n我逐渐意识到，我们生活中许多经历与我们的期望直接相关。当我们刚开始时，我们的期望很低，相对容易实现。随着我们前进并站在更高的高度上，我们开始期待更多，这可能不是线性增长的。当你有1000个星星时，再获得100个星星听起来并不像当你什么都没有时那么令人印象深刻。当你有1000颗星星时，你"',
    messageCount: 2,
    origin: "https://antfu.me",
    originPageUrl: "https://antfu.me/posts/mental-health-oss",
    originPageTitle: "Mental Health in Open Source",
    createdAt: "2024-03-21T13:28:31.199Z",
    updatedAt: "2024-03-21T13:29:15.271Z",
  },
  {
    id: "65fc35f795de0ee1341fe27a",
    userId: "65fc2a2196ea5f02878995b2",
    title: "Mental Health in Open Source",
    lastMessage: "",
    messageCount: 0,
    origin: "https://antfu.me",
    originPageUrl: "https://antfu.me/posts/mental-health-oss",
    originPageTitle: "Mental Health in Open Source",
    createdAt: "2024-03-21T13:28:23.262Z",
    updatedAt: "2024-03-21T13:28:23.262Z",
  },
  {
    id: "65fc35cf95de0ee1341fe276",
    userId: "65fc2a2196ea5f02878995b2",
    title: "The Dark Side of Open Source - kettanaito.com",
    lastMessage:
      "# 网页内容摘要\n\n## The Dark Side of Open Source - kettanaito.com\n关于我博客文化—2022年6月13日开源的阴暗面\n\n### 状态检查\n- 从开源作者的角度写作\n- 贡献者和作者在开源方面有显著区别\n- 开源是学习和交友的好地方\n\n### 享受被发现之前的时光\n- 建立伟大的东西，人们会跟随\n- 享受项目还未被发现时的独特感觉\n\n### 它是产品，而不是功能\n- 开源库是产品\n- 需要品牌化\n- 作者需要寻找项目的财务支持\n\n### 开源中的金钱\n- 开源不是为了金钱\n- 作者需要外部来源的财务支持\n- 开源并非关于金钱\n\n这篇文章探讨了开源的阴暗面，强调了作者与贡献者之间的区别，以及在开源世界中寻找财务支持的重要性。",
    messageCount: 2,
    origin: "https://kettanaito.com",
    originPageUrl: "https://kettanaito.com/blog/the-dark-side-of-open-source",
    originPageTitle: "The Dark Side of Open Source - kettanaito.com",
    createdAt: "2024-03-21T13:27:43.453Z",
    updatedAt: "2024-03-21T13:27:51.709Z",
  },
  {
    id: "65fc2f8396ea5f02878995c4",
    userId: "65fc2a2196ea5f02878995b2",
    title: "Mental Health in Open Source",
    lastMessage:
      "Velocity is a term commonly used in agile project management to measure the rate at which a team delivers work. It is calculated by summing up the estimates of the work completed in a sprint. A higher velocity indicates that the team is delivering more work consistently, while a lower velocity may indicate issues or challenges impacting productivity.",
    messageCount: 6,
    origin: "https://antfu.me",
    originPageUrl: "https://antfu.me/posts/mental-health-oss",
    originPageTitle: "Mental Health in Open Source",
    createdAt: "2024-03-21T13:00:51.184Z",
    updatedAt: "2024-03-21T13:03:11.447Z",
  },
  {
    id: "65fc2f3a96ea5f02878995c0",
    userId: "65fc2a2196ea5f02878995b2",
    title: "The Dark Side of Open Source - kettanaito.com",
    lastMessage:
      "抱歉，我不知道你想要总结的具体内容是什么。请提供更多信息或者具体问题，我会尽力帮助你。",
    messageCount: 2,
    origin: "https://kettanaito.com",
    originPageUrl: "https://kettanaito.com/blog/the-dark-side-of-open-source",
    originPageTitle: "The Dark Side of Open Source - kettanaito.com",
    createdAt: "2024-03-21T12:59:38.190Z",
    updatedAt: "2024-03-21T12:59:41.773Z",
  },
  {
    id: "65fc2e9396ea5f02878995b9",
    userId: "65fc2a2196ea5f02878995b2",
    title: "The Dark Side of Open Source - kettanaito.com",
    lastMessage:
      "开源软件存在一些缺点，如支持和文档有限，可能存在安全漏洞，以及在使用或分发开源软件时未遵守许可证可能带来的法律风险。",
    messageCount: 6,
    origin: "https://kettanaito.com",
    originPageUrl: "https://kettanaito.com/blog/the-dark-side-of-open-source",
    originPageTitle: "The Dark Side of Open Source - kettanaito.com",
    createdAt: "2024-03-21T12:56:51.109Z",
    updatedAt: "2024-03-21T12:57:44.729Z",
  },
  {
    id: "65fc2dff96ea5f02878995b6",
    userId: "65fc2a2196ea5f02878995b2",
    title: "The Dark Side of Open Source - kettanaito.com",
    lastMessage:
      "开源世界的挑战包括项目的可持续性和维护、社区管理、安全漏洞的管理、项目的治理和决策过程等。这些挑战需要开源社区和项目领导者共同努力解决，以确保开源项目的长期成功和发展。",
    messageCount: 6,
    origin: "https://kettanaito.com",
    originPageUrl: "https://kettanaito.com/blog/the-dark-side-of-open-source",
    originPageTitle: "The Dark Side of Open Source - kettanaito.com",
    createdAt: "2024-03-21T12:54:23.640Z",
    updatedAt: "2024-03-21T13:06:08.183Z",
  },
]
