export const mockSources = [
  {
    url: 'https://www.threads.net/@yushengliin/post/DFOii6fTca-',
    title: 'refly：高效智能的AI內容創作工具 - Threads',
    pageContent:
      'refly 是一款集搜索、筆記、思維導圖與AI寫作為一體的超級工具，幫助用戶將想法高效轉化為文字，從靈感捕捉到內容創作，提供全方位的支持，讓創作過程更加流暢 ...',
    metadata: {
      originalLocale: 'en',
      originalQuery: 'refly 的定义是什么？',
      translatedQuery: undefined,
      isTranslated: false,
      url: 'https://www.threads.net/@yushengliin/post/DFOii6fTca-',
      score: 0.8933094143867493,
      source: 'https://www.threads.net/@yushengliin/post/DFOii6fTca-',
      title: 'refly：高效智能的AI內容創作工具 - Threads',
      sourceType: 'webSearch',
    },
  },
  {
    url: 'https://www.cnblogs.com/Agora/p/18671366',
    title: 'Kyutai开源端侧模型Helium -1 preview；FoloToy内测「超级智能体」',
    pageContent:
      'Refly 是一个基于自由画布的AI 原生创作引擎，旨在通过多线程对话、知识库集成、上下文记忆和智能搜索技术，帮助用户将创意转化为高质量内容。 该平台覆盖了 ...',
    metadata: {
      originalLocale: 'zh-hans',
      originalQuery: 'refly 的定义是什么？',
      translatedQuery: undefined,
      isTranslated: false,
      url: 'https://www.cnblogs.com/Agora/p/18671366',
      score: 0.8723474144935608,
      source: 'https://www.cnblogs.com/Agora/p/18671366',
      title: 'Kyutai开源端侧模型Helium -1 preview；FoloToy内测「超级智能体」',
      sourceType: 'webSearch',
    },
  },
  {
    url: 'https://www.aisharenet.com/refly-zhengshikaifangben/',
    title: 'Refly 正式开放注册，文字创作者的最佳工作平台 - 首席AI分享圈',
    pageContent:
      'Refly 是一个基于「 自由画布 」理念构建的AI 原生内容创作平台，通过多线程对话、知识库整合、上下文记忆、智能搜索与可见即可得的AI 文档编辑器，为用户 ...',
    metadata: {
      originalLocale: 'zh-hans',
      originalQuery: 'refly 的定义是什么？',
      translatedQuery: undefined,
      isTranslated: false,
      url: 'https://www.aisharenet.com/refly-zhengshikaifangben/',
      score: 0.8714748620986938,
      source: 'https://www.aisharenet.com/refly-zhengshikaifangben/',
      title: 'Refly 正式开放注册，文字创作者的最佳工作平台 - 首席AI分享圈',
      sourceType: 'webSearch',
    },
  },
  {
    url: 'https://www.163.com/dy/article/JMOURKU605567BLV.html',
    title: 'Refly 是一个开源的AI..._手机网易网',
    pageContent:
      'Refly是一个开源的AI原生创作引擎，提供了一个直观的自由格式画布界面，集成了多线程对话、AI知识库集成、上下文记忆、智能搜索、所见即所得的AI编辑器 ...',
    metadata: {
      originalLocale: 'zh-hans',
      originalQuery: 'refly 的定义是什么？',
      translatedQuery: undefined,
      isTranslated: false,
      url: 'https://www.163.com/dy/article/JMOURKU605567BLV.html',
      score: 0.8688268065452576,
      source: 'https://www.163.com/dy/article/JMOURKU605567BLV.html',
      title: 'Refly 是一个开源的AI..._手机网易网',
      sourceType: 'webSearch',
    },
  },
  {
    url: 'https://top.aibase.com/tool/refly',
    title: 'Refly使用入口地址Ai网站最新工具和软件app下载 - AIbase',
    pageContent:
      'Refly是一个AI Native创作引擎，通过多线程对话、知识库整合、上下文记忆和智能搜索等技术，帮助用户将创意转化为优质内容。 它覆盖了学术研究、技术文档等20+专业场景模板， ...',
    metadata: {
      originalLocale: 'zh-hans',
      originalQuery: 'refly 的定义是什么？',
      translatedQuery: undefined,
      isTranslated: false,
      url: 'https://top.aibase.com/tool/refly',
      score: 0.8679338097572327,
      source: 'https://top.aibase.com/tool/refly',
      title: 'Refly使用入口地址Ai网站最新工具和软件app下载 - AIbase',
      sourceType: 'webSearch',
    },
  },
  {
    url: 'https://c.m.163.com/news/a/JMOURKU605567BLV.html',
    title: 'Refly 是一个开源的AI... - 网易新闻',
    pageContent:
      'Refly 是一个开源的AI 原生创作引擎，提供了一个直观的自由格式画布界面，集成了多线程对话、AI 知识库集成、上下文记忆、智能搜索、所见即所得的AI ...',
    metadata: {
      originalLocale: 'zh-hans',
      originalQuery: 'refly 的定义是什么？',
      translatedQuery: undefined,
      isTranslated: false,
      url: 'https://c.m.163.com/news/a/JMOURKU605567BLV.html',
      score: 0.8652240633964539,
      source: 'https://c.m.163.com/news/a/JMOURKU605567BLV.html',
      title: 'Refly 是一个开源的AI... - 网易新闻',
      sourceType: 'webSearch',
    },
  },
  {
    url: 'https://www.aibase.com/zh/tool/35128',
    title: 'Refly-基于自由画布的创作平台 - AIbase',
    pageContent:
      'Refly是一个AI Native创作引擎，通过多线程对话、知识库整合、上下文记忆和智能搜索等技术，帮助用户将创意转化为优质内容。它覆盖了学术研究、技术文档等20+专业场景 ...',
    metadata: {
      originalLocale: 'zh-hans',
      originalQuery: 'refly 的定义是什么？',
      translatedQuery: undefined,
      isTranslated: false,
      url: 'https://www.aibase.com/zh/tool/35128',
      score: 0.8643104434013367,
      source: 'https://www.aibase.com/zh/tool/35128',
      title: 'Refly-基于自由画布的创作平台 - AIbase',
      sourceType: 'webSearch',
    },
  },
  {
    url: 'https://apps.shopify.com/refly?locale=zh-CN',
    title: 'Refly: AI-Powered Multi-Channel Customer Service for Shopify',
    pageContent:
      'Refly是一个AI驱动的工具，可以在多个渠道（包括Shopify、聊天小部件等）自动化客户服务。 适用于任何规模的企业，Refly简化了客户互动管理，自动化常规任务，并提供个性化 ...',
    metadata: {
      originalLocale: 'zh-hans',
      originalQuery: 'refly 的定义是什么？',
      translatedQuery: undefined,
      isTranslated: false,
      url: 'https://apps.shopify.com/refly?locale=zh-CN',
      score: 0.8558511734008789,
      source: 'https://apps.shopify.com/refly?locale=zh-CN',
      title: 'Refly: AI-Powered Multi-Channel Customer Service for Shopify',
      sourceType: 'webSearch',
    },
  },
  {
    url: 'https://github.com/refly-ai/refly/blob/main/README_CN.md',
    title: 'refly/README_CN.md at main · refly-ai/refly - GitHub',
    pageContent:
      'Refly 是一个开源的AI 原生创作引擎。Refly 直观的自由画布界面集成了多线程对话、RAG 检索流程、上下文记忆、智能搜索和AI 文档编辑等功能，让您轻松地将创意转化为 ...',
    metadata: {
      originalLocale: 'zh-hans',
      originalQuery: 'refly 的定义是什么？',
      translatedQuery: undefined,
      isTranslated: false,
      url: 'https://github.com/refly-ai/refly/blob/main/README_CN.md',
      score: 0.854884684085846,
      source: 'https://github.com/refly-ai/refly/blob/main/README_CN.md',
      title: 'refly/README_CN.md at main · refly-ai/refly - GitHub',
      sourceType: 'webSearch',
    },
  },
  {
    url: 'https://top.aibase.com/topic/%E6%99%BA%E8%83%BD%E6%90%9C%E7%B4%A2',
    title: '最新Ai智能搜索网站工具和软件推荐_AiBase产品库',
    pageContent:
      'Refly. 基于自由画布的创作平台，激发创作灵感。 Refly是一个AI Native创作引擎，通过多线程对话、知识库整合、上下文记忆和智能搜索等技术，帮助用户将创意转化为优质 ...',
    metadata: {
      originalLocale: 'zh-hans',
      originalQuery: 'refly 的定义是什么？',
      translatedQuery: undefined,
      isTranslated: false,
      url: 'https://top.aibase.com/topic/%E6%99%BA%E8%83%BD%E6%90%9C%E7%B4%A2',
      score: 0.8418256044387817,
      source: 'https://top.aibase.com/topic/%E6%99%BA%E8%83%BD%E6%90%9C%E7%B4%A2',
      title: '最新Ai智能搜索网站工具和软件推荐_AiBase产品库',
      sourceType: 'webSearch',
    },
  },
  {
    url: 'https://www.cnblogs.com/wuhuacong/archive/2012/03/30/2426091.html',
    title: '利用Refly和CodeDom实现代码的动态生成和动态编译- 伍华聪- 博客园',
    pageContent:
      'Refly则是国外一个开发者对CodeDom进行封装，目的是使得Codedom的实现更加方便易懂，和CodeDom的使用对比，代码更加简洁优雅，不过要了解整体的东西 ...',
    metadata: {
      originalLocale: 'zh-hans',
      originalQuery: 'refly 的定义是什么？',
      translatedQuery: undefined,
      isTranslated: false,
      url: 'https://www.cnblogs.com/wuhuacong/archive/2012/03/30/2426091.html',
      score: 0.8198933005332947,
      source: 'https://www.cnblogs.com/wuhuacong/archive/2012/03/30/2426091.html',
      title: '利用Refly和CodeDom实现代码的动态生成和动态编译- 伍华聪- 博客园',
      sourceType: 'webSearch',
    },
  },
  {
    url: 'https://dread.run/',
    title: '帝阅- 专注信息摘要的智能侍读助理',
    pageContent:
      '1.Refly是一个AI原生创作平台，旨在简化创作流程。 2.平台基于LangGraph技术，提供强大的AI功能。 3.Refly开源，代码仓库在GitHub上可供访问 ...',
    metadata: {
      originalLocale: 'zh-hans',
      originalQuery: 'refly 的定义是什么？',
      translatedQuery: undefined,
      isTranslated: false,
      url: 'https://dread.run/',
      score: 0.8198933005332947,
      source: 'https://dread.run/',
      title: '帝阅- 专注信息摘要的智能侍读助理',
      sourceType: 'webSearch',
    },
  },
  {
    url: 'https://developer.aliyun.com/article/326893',
    title: '利用Refly和CodeDom实现代码的动态生成和动态编译',
    pageContent:
      'Refly则是国外一个开发者对CodeDom进行封装，目的是使得Codedom的实现更加方便易懂，和CodeDom的使用对比，代码更加简洁优雅，不过要了解整体的东西，也需要对CodeDOM ...',
    metadata: {
      originalLocale: 'zh-hans',
      originalQuery: 'refly 的定义是什么？',
      translatedQuery: undefined,
      isTranslated: false,
      url: 'https://developer.aliyun.com/article/326893',
      score: 0.815232515335083,
      source: 'https://developer.aliyun.com/article/326893',
      title: '利用Refly和CodeDom实现代码的动态生成和动态编译',
      sourceType: 'webSearch',
    },
  },
  {
    url: 'https://www.aihub.cn/tools/writing/refly/',
    title: 'Refly.ai：AI驱动的专业内容创作引擎 - AIHub',
    pageContent:
      'Refly.ai 是一款专为专业内容创作设计的AI驱动平台，通过多线程对话、知识整合、上下文记忆和智能搜索功能，帮助用户将创意快速转化为高质量内容。',
    metadata: {
      originalLocale: 'zh-hans',
      originalQuery: 'refly 的定义是什么？',
      translatedQuery: undefined,
      isTranslated: false,
      url: 'https://www.aihub.cn/tools/writing/refly/',
      score: 0.8068526387214661,
      source: 'https://www.aihub.cn/tools/writing/refly/',
      title: 'Refly.ai：AI驱动的专业内容创作引擎 - AIHub',
      sourceType: 'webSearch',
    },
  },
  {
    url: 'https://www.threads.net/@yongshuai1013/post/DFPqDQURqkF',
    title: '開源分享AI智慧創作工具：refly，它是一個集成了搜索、筆記軟體',
    pageContent:
      '開源分享AI智慧創作工具：refly，它是一個集成了搜索、筆記軟體、心智圖以及AI寫作的超級工具，用它可以更高效的把想法變成文字.',
    metadata: {
      originalLocale: 'zh-hans',
      originalQuery: 'refly 的定义是什么？',
      translatedQuery: undefined,
      isTranslated: false,
      url: 'https://www.threads.net/@yongshuai1013/post/DFPqDQURqkF',
      score: 0.7839884757995605,
      source: 'https://www.threads.net/@yongshuai1013/post/DFPqDQURqkF',
      title: '開源分享AI智慧創作工具：refly，它是一個集成了搜索、筆記軟體',
      sourceType: 'webSearch',
    },
  },
  {
    url: 'https://t.cj.sina.com.cn/articles/view/2194035935/m82c654df03301e9hi?from=tech',
    title: 'AI创作引擎项目Refly.AI刚正式开源了 - 新浪财经',
    pageContent:
      'AI创作引擎项目Refly.AI刚正式开源了github.com/refly-ai/refly/Refly 是一个开源的AI 原生创作引擎。Refly 直观的自由画布界面集成了多线程对话、RAG ...',
    metadata: {
      originalLocale: 'zh-hans',
      originalQuery: 'refly 的定义是什么？',
      translatedQuery: undefined,
      isTranslated: false,
      url: 'https://t.cj.sina.com.cn/articles/view/2194035935/m82c654df03301e9hi?from=tech',
      score: 0.7520125508308411,
      source: 'https://t.cj.sina.com.cn/articles/view/2194035935/m82c654df03301e9hi?from=tech',
      title: 'AI创作引擎项目Refly.AI刚正式开源了 - 新浪财经',
      sourceType: 'webSearch',
    },
  },
  {
    url: 'https://www.ftium4.com/ux-weekly-215.html',
    title: '体验碎周报第215 期（2024.12.23） - 龙爪槐守望者',
    pageContent:
      'Refly——自由画布笔记 ... 把笔记放在画布上，通过多线程对话、知识库整合、上下文记忆和智能搜索，帮助用户轻松将创意转化为高质量内容。该平台支持超过20 种 ...',
    metadata: {
      originalLocale: 'zh-hans',
      originalQuery: 'refly 的定义是什么？',
      translatedQuery: undefined,
      isTranslated: false,
      url: 'https://www.ftium4.com/ux-weekly-215.html',
      score: 0.7386690378189087,
      source: 'https://www.ftium4.com/ux-weekly-215.html',
      title: '体验碎周报第215 期（2024.12.23） - 龙爪槐守望者',
      sourceType: 'webSearch',
    },
  },
  {
    url: 'https://x.com/aigclink/status/1882778663164461111',
    title: 'AIGCLINK on X: "很棒的一个AI智能创作工具：refly，它是一个集成了 ...',
    pageContent:
      '很棒的一个AI智能创作工具：refly，它是一个集成了搜索、笔记软件、思维导图以及AI写作的超级工具，用它可以更高效的把想法变成文字自由画布界面设计， ...',
    metadata: {
      originalLocale: 'zh-hans',
      originalQuery: 'refly 的定义是什么？',
      translatedQuery: undefined,
      isTranslated: false,
      url: 'https://x.com/aigclink/status/1882778663164461111',
      score: 0.7371581792831421,
      source: 'https://x.com/aigclink/status/1882778663164461111',
      title: 'AIGCLINK on X: "很棒的一个AI智能创作工具：refly，它是一个集成了 ...',
      sourceType: 'webSearch',
    },
  },
  {
    url: 'https://x.com/tuturetom/status/1868585642529284566',
    title: 'Tom Huang on X: "  大家好！  很高兴向大家介绍我们的AI 写作产品 ...',
    pageContent:
      '大家好！ 很高兴向大家介绍我们的AI 写作产品—— Refly，这是一款革新性的AI Native 内容创作引擎！⚡️ Refly 是基于「自由画布 ‍ ‍ 」理念打造的AI Native ...',
    metadata: {
      originalLocale: 'zh-hans',
      originalQuery: 'refly 的定义是什么？',
      translatedQuery: undefined,
      isTranslated: false,
      url: 'https://x.com/tuturetom/status/1868585642529284566',
      score: 0.7256486415863037,
      source: 'https://x.com/tuturetom/status/1868585642529284566',
      title: 'Tom Huang on X: "  大家好！  很高兴向大家介绍我们的AI 写作产品 ...',
      sourceType: 'webSearch',
    },
  },
  {
    url: 'https://zhidao.baidu.com/question/451012173.html',
    title: 'refly是什么意思? - 百度知道',
    pageContent: 'refly是"答复"的意思。 ...全文.',
    metadata: {
      originalLocale: 'zh-hans',
      originalQuery: 'refly 的定义是什么？',
      translatedQuery: undefined,
      isTranslated: false,
      url: 'https://zhidao.baidu.com/question/451012173.html',
      score: 0.7185943722724915,
      source: 'https://zhidao.baidu.com/question/451012173.html',
      title: 'refly是什么意思? - 百度知道',
      sourceType: 'webSearch',
    },
  },
  {
    url: 'https://ainote.tw/refly-ai-creation-platform-explained/',
    title: 'Refly AI 創作平臺全面解析 - 奕昇AI學習平台',
    pageContent:
      'Refly 的核心概念為自由畫布，讓創作者可以在一個開放的環境中自由探索與 ... 如果您需要一款功能強大且靈活的AI 創作工具，Refly 無疑是最佳選擇！',
    metadata: {
      originalLocale: 'zh-hans',
      originalQuery: 'refly 的定义是什么？',
      translatedQuery: undefined,
      isTranslated: false,
      url: 'https://ainote.tw/refly-ai-creation-platform-explained/',
      score: 0.7000752091407776,
      source: 'https://ainote.tw/refly-ai-creation-platform-explained/',
      title: 'Refly AI 創作平臺全面解析 - 奕昇AI學習平台',
      sourceType: 'webSearch',
    },
  },
  {
    url: 'https://www.waytoagi.com/zh/question/87173',
    title: '与知识库对话- flowith 2.0与refly的区别具体在哪里？ - WaytoAGI',
    pageContent:
      'Flowith 2.0 与Refly 的区别主要体现在以下方面：. 功能定位：Refly 是一款国产应用，是全站式的文本创作工具，集成了“知识库+自由画布+AI 搜索+内容编辑”等功能，覆盖主题 ...',
    metadata: {
      originalLocale: 'zh-hans',
      originalQuery: 'refly 的定义是什么？',
      translatedQuery: undefined,
      isTranslated: false,
      url: 'https://www.waytoagi.com/zh/question/87173',
      score: 0.6388352513313293,
      source: 'https://www.waytoagi.com/zh/question/87173',
      title: '与知识库对话- flowith 2.0与refly的区别具体在哪里？ - WaytoAGI',
      sourceType: 'webSearch',
    },
  },
  {
    url: 'https://www.bgrdh.com/sites/49214.html',
    title: 'Refly-基于“自由画布”理念的AI 原生内容创作引擎 - 办公人导航',
    pageContent:
      'Refly 的适用范围非常广泛，涵盖了学术研究、技术文档编写、投资分析、法律文献 ... 用户可以根据自己的需求选择专业场景模板，并通过上下文记忆和智能搜索功能优化创作流程。',
    metadata: {
      originalLocale: 'zh-hans',
      originalQuery: 'refly 的定义是什么？',
      translatedQuery: undefined,
      isTranslated: false,
      url: 'https://www.bgrdh.com/sites/49214.html',
      score: 0.5404388308525085,
      source: 'https://www.bgrdh.com/sites/49214.html',
      title: 'Refly-基于“自由画布”理念的AI 原生内容创作引擎 - 办公人导航',
      sourceType: 'webSearch',
    },
  },
  {
    url: 'https://www.youtube.com/watch?v=5efKJWEvR94',
    title: '介绍AI自由画板写作工具Refly.ai 以及使用其逐步创建一个详细的游戏 ...',
    pageContent:
      '本片介绍一个AI自由画板写作工具——Refly.ai，并使用其逐步创建一个详细的游戏项目规则。视频只有3分多钟，很容易看完。稍后我会整理详细的各部分提示发 ...',
    metadata: {
      originalLocale: 'zh-hans',
      originalQuery: 'refly 的定义是什么？',
      translatedQuery: undefined,
      isTranslated: false,
      url: 'https://www.youtube.com/watch?v=5efKJWEvR94',
      score: 0.4929509162902832,
      source: 'https://www.youtube.com/watch?v=5efKJWEvR94',
      title: '介绍AI自由画板写作工具Refly.ai 以及使用其逐步创建一个详细的游戏 ...',
      sourceType: 'webSearch',
    },
  },
  {
    url: 'https://ai-bot.cn/refly/',
    title: 'Refly - AI原生内容创作平台，结合自由画布与多种AI 功能 - AI工具集',
    pageContent:
      'Refly的应用场景. 学术研究：帮助研究人员整理思路、构建研究框架，快速生成文献 ... 相关文章. Manga Image Translator – 开源漫画图片文字翻译工具，多语言翻译无 ...',
    metadata: {
      originalLocale: 'zh-hans',
      originalQuery: 'refly 的定义是什么？',
      translatedQuery: undefined,
      isTranslated: false,
      url: 'https://ai-bot.cn/refly/',
      score: 0.4144248068332672,
      source: 'https://ai-bot.cn/refly/',
      title: 'Refly - AI原生内容创作平台，结合自由画布与多种AI 功能 - AI工具集',
      sourceType: 'webSearch',
    },
  },
  {
    url: 'https://x.com/nishuang/status/1882819143860113520',
    title: '倪爽- 上个月我推荐大家试用“自由画布”式AI 创作工具Refly - X',
    pageContent:
      '上个月我推荐大家试用“自由画布”式AI 创作工具Refly，当时我说了两个感受，没想到背后都有深意我说他们最慷慨，没想到今天他们把整个项目开源了 ， ...',
    metadata: {
      originalLocale: 'zh-hans',
      originalQuery: 'refly 的定义是什么？',
      translatedQuery: undefined,
      isTranslated: false,
      url: 'https://x.com/nishuang/status/1882819143860113520',
      score: 0.39981165528297424,
      source: 'https://x.com/nishuang/status/1882819143860113520',
      title: '倪爽- 上个月我推荐大家试用“自由画布”式AI 创作工具Refly - X',
      sourceType: 'webSearch',
    },
  },
  {
    url: 'https://aiguide.cc/sites/14379.html',
    title: 'Refly | AI智库导航-aiguide.cc',
    pageContent:
      '主要应用场景. 内容创作：适用于各种需要快速生成高质量内容的创作者，如 ... 注册与登录：访问Refly的官方网站或相关应用平台，注册并登录账号。 创建画布：在 ...',
    metadata: {
      originalLocale: 'zh-hans',
      originalQuery: 'refly 的定义是什么？',
      translatedQuery: undefined,
      isTranslated: false,
      url: 'https://aiguide.cc/sites/14379.html',
      score: 0.38676342368125916,
      source: 'https://aiguide.cc/sites/14379.html',
      title: 'Refly | AI智库导航-aiguide.cc',
      sourceType: 'webSearch',
    },
  },
  {
    url: 'https://www.yjpoo.com/site/5081.html',
    title: 'Refly Ai：一个开源的AI原生创作引擎 - 映技派',
    pageContent:
      'Refly AI特别适合需要深度思考和结构化组织的创作场景，如学术研究、技术文档编写等，Refly Ai现已集成最火的DeepSeek R1。 Refly Ai.webp. Refly Ai核心功能：. Refly AI 的 ...',
    metadata: {
      originalLocale: 'zh-hans',
      originalQuery: 'refly 的定义是什么？',
      translatedQuery: undefined,
      isTranslated: false,
      url: 'https://www.yjpoo.com/site/5081.html',
      score: 0.3656831681728363,
      source: 'https://www.yjpoo.com/site/5081.html',
      title: 'Refly Ai：一个开源的AI原生创作引擎 - 映技派',
      sourceType: 'webSearch',
    },
  },
  {
    url: 'http://npses.ezsale.tw/upload/0402240001.ppt',
    title: '[PPT] 資訊安全基本認知教育訓練',
    pageContent:
      '不論學校內部採用多強大的防火牆系統、防毒軟體、或其他資安技術軟硬體設施 ... http://www.refly.net/passwordchecker; http://www.microsoft.com/taiwan/athome ...',
    metadata: {
      originalLocale: 'zh-hans',
      originalQuery: 'refly 的定义是什么？',
      translatedQuery: undefined,
      isTranslated: false,
      url: 'http://npses.ezsale.tw/upload/0402240001.ppt',
      score: 0.25091278553009033,
      source: 'http://npses.ezsale.tw/upload/0402240001.ppt',
      title: '[PPT] 資訊安全基本認知教育訓練',
      sourceType: 'webSearch',
    },
  },
  {
    url: 'https://docs.refly.ai/zh/guide/configuration',
    title: '配置说明| Refly 文档',
    pageContent:
      'MinIO ​ Refly 需要两个MinIO 实例： 内部：用于存储画布、资源和文档数据，通常设置为私有可见性。 外部：用于存储上传的文件，通常设置为公开可见性。',
    metadata: {
      originalLocale: 'zh-hans',
      originalQuery: 'refly 的定义是什么？',
      translatedQuery: undefined,
      isTranslated: false,
      url: 'https://docs.refly.ai/zh/guide/configuration',
      score: 0.24508501589298248,
      source: 'https://docs.refly.ai/zh/guide/configuration',
      title: '配置说明| Refly 文档',
      sourceType: 'webSearch',
    },
  },
  {
    url: 'https://chromewebstore.google.com/detail/refly-ai-native-%E5%88%9B%E4%BD%9C%E5%BC%95%E6%93%8E/lecbjbapfkinmikhadakbclblnemmjpd?hl=zh-CN',
    title: 'Refly - AI Native 创作引擎- Chrome 应用商店',
    pageContent:
      '基于自由画布的创作平台，通过多线程对话、知识库整合、上下文记忆、智能搜索和AI 文档编辑器，轻松将想法转化为优质内容。',
    metadata: {
      originalLocale: 'zh-hans',
      originalQuery: 'refly 的定义是什么？',
      translatedQuery: undefined,
      isTranslated: false,
      url: 'https://chromewebstore.google.com/detail/refly-ai-native-%E5%88%9B%E4%BD%9C%E5%BC%95%E6%93%8E/lecbjbapfkinmikhadakbclblnemmjpd?hl=zh-CN',
      score: 0.23091977834701538,
      source:
        'https://chromewebstore.google.com/detail/refly-ai-native-%E5%88%9B%E4%BD%9C%E5%BC%95%E6%93%8E/lecbjbapfkinmikhadakbclblnemmjpd?hl=zh-CN',
      title: 'Refly - AI Native 创作引擎- Chrome 应用商店',
      sourceType: 'webSearch',
    },
  },
];
