# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import aero_pb2 as aero__pb2


class AeroStub(object):
    """The aero service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ParseHTML = channel.unary_unary(
                '/aero.Aero/ParseHTML',
                request_serializer=aero__pb2.ParseHTMLRequest.SerializeToString,
                response_deserializer=aero__pb2.ParseHTMLResult.FromString,
                )


class AeroServicer(object):
    """The aero service definition.
    """

    def ParseHTML(self, request, context):
        """Parse HTML
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AeroServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ParseHTML': grpc.unary_unary_rpc_method_handler(
                    servicer.ParseHTML,
                    request_deserializer=aero__pb2.ParseHTMLRequest.FromString,
                    response_serializer=aero__pb2.ParseHTMLResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aero.Aero', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Aero(object):
    """The aero service definition.
    """

    @staticmethod
    def ParseHTML(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/aero.Aero/ParseHTML',
            aero__pb2.ParseHTMLRequest.SerializeToString,
            aero__pb2.ParseHTMLResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
