# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aero.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\naero.proto\x12\x04\x61\x65ro\"^\n\x10ParseHTMLRequest\x12\x0c\n\x04html\x18\x01 \x01(\t\x12)\n\rselector_type\x18\x02 \x01(\x0e\x32\x12.aero.SelectorType\x12\x11\n\tselectors\x18\x03 \x03(\t\"\\\n\x0cHTMLFragment\x12)\n\rselector_type\x18\x01 \x01(\x0e\x32\x12.aero.SelectorType\x12\x10\n\x08selector\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\"8\n\x0fParseHTMLResult\x12%\n\tfragments\x18\x01 \x03(\x0b\x32\x12.aero.HTMLFragment*\x19\n\x0cSelectorType\x12\t\n\x05XPath\x10\x00\x32\x44\n\x04\x41\x65ro\x12<\n\tParseHTML\x12\x16.aero.ParseHTMLRequest\x1a\x15.aero.ParseHTMLResult\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aero_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SELECTORTYPE']._serialized_start=268
  _globals['_SELECTORTYPE']._serialized_end=293
  _globals['_PARSEHTMLREQUEST']._serialized_start=20
  _globals['_PARSEHTMLREQUEST']._serialized_end=114
  _globals['_HTMLFRAGMENT']._serialized_start=116
  _globals['_HTMLFRAGMENT']._serialized_end=208
  _globals['_PARSEHTMLRESULT']._serialized_start=210
  _globals['_PARSEHTMLRESULT']._serialized_end=266
  _globals['_AERO']._serialized_start=295
  _globals['_AERO']._serialized_end=363
# @@protoc_insertion_point(module_scope)
