import { type CustomPrompt, PromptActionType } from '../types/custom-prompt';

export const CustomPromptList: CustomPrompt[] = [
  {
    id: '3',
    type: PromptActionType.selectionAction,
    title: '解释',
    content: `解释这个文本并说明其中使用的任何技术术语。`,
    authorId: 'author_id_1',
    pinned: true,
    directSend: false,
    iconName: 'book',
    position: 1,
    systemPromptId: '1',
    systemKey: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '6',
    type: PromptActionType.selectionAction,
    title: '翻译',
    content: `将这段文字翻译成中文。`,
    authorId: 'author_id_2',
    pinned: true,
    directSend: false,
    iconName: 'translate',
    position: 2,
    systemPromptId: '2',
    systemKey: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '4',
    type: PromptActionType.selectionAction,
    title: '摘要',
    content: `用原文语言概括这段文字。`,
    authorId: 'author_id_3',
    pinned: true,
    directSend: false,
    iconName: 'topic',
    position: 3,
    systemPromptId: '3',
    systemKey: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '8',
    type: PromptActionType.selectionAction,
    title: '解释代码',
    content: `解释以下代码：
        \`\`\`
        $[text]
        \`\`\``,
    authorId: 'author_id_4',
    pinned: false,
    directSend: false,
    iconName: 'code',
    position: 4,
    systemPromptId: '4',
    systemKey: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '2',
    type: PromptActionType.selectionAction,
    title: '重写',
    content: `重新表述这段文字。`,
    authorId: 'author_id_5',
    pinned: false,
    directSend: false,
    iconName: 'write',
    position: 5,
    systemPromptId: '5',
    systemKey: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '1',
    type: PromptActionType.selectionAction,
    title: '问答',
    content: `回答这个问题。`,
    authorId: 'author_id_6',
    pinned: false,
    directSend: false,
    iconName: 'help',
    position: 6,
    systemPromptId: '6',
    systemKey: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '5',
    type: PromptActionType.selectionAction,
    title: '语法',
    content: `校对并纠正这段文字。`,
    authorId: 'author_id_7',
    pinned: false,
    directSend: false,
    iconName: 'text-message',
    position: 7,
    systemPromptId: '7',
    systemKey: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '7',
    type: PromptActionType.selectionAction,
    title: '扩写',
    content: `详细说明这段文字。`,
    authorId: 'author_id_8',
    pinned: false,
    directSend: false,
    iconName: 'expand-text-input',
    position: 8,
    systemPromptId: '8',
    systemKey: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
const getModePrompt = (modeId: string) => {
  return CustomPromptList.filter((item) => item.id === modeId)?.[0]?.content;
};
